### ISSUE TITLE
Render functions in meta don't get composed into stories

### ISSUE THREAD

**Issue by TeaSeaLancs** [storybookjs/testing-react#104]
**Describe the bug**

If you have a story file with a render function in the `meta`, this render function is used correctly when viewing the story in Storybook, but not when composed using `@storybook/testing-react`

**To Reproduce**
* Create a new story file
* In the meta for the story file, specify a `render` function
* Compose stories for that file

**Expected behavior**
* The render function in the meta should be used as the render function for the composed stories.

**Comment by yannbf** [comment]
Closed by #103, should be available in 1.3.0! Thank you so much @TeaSeaLancs !
