### ISSUE TITLE
@storybook/preview-web stops exporting WebProjectAnnotations at 6.5.0

### ISSUE THREAD

**Issue by dakotalightning** [storybookjs/testing-react#106]
**Describe the bug**

```sh
../../node_modules/@storybook/testing-react/dist/types.d.ts:2:15 - error TS2305: Module '"@storybook/preview-web"' has no exported member 'WebProjectAnnotations'.

2 import type { WebProjectAnnotations } from '@storybook/preview-web';
```

**To Reproduce**
Use any @storybook version above `v6.5.0`

Should be `~6.4.0`
https://github.com/storybookjs/testing-react/blob/16f7182de1dfa9b186ac5a8957760974577008f6/package.json#L79

Looks like they remove `WebProjectAnnotations` export at `v6.5.0-alpha.53`. Seems like a breaking change to me. 🤷🏽‍♂️ 
https://github.com/storybookjs/storybook/commit/bcf7e4d03a1e58a1862379adbfd98d1be67194e4#diff-a10f71fb35c8a250ffdfe123e528271e550f05469a3e09e1ae746555707972a5

**Comment by dakotalightning** [comment]
https://github.com/storybookjs/storybook/issues/16797

**Comment by sakit0** [comment]
@yannbf 

I cannot use Storybook 6.5 because of this problem.
Can this problem be resolved?

**Comment by ingokpp** [comment]
I'm also struggling to upgrade to 6.5 because of this.

**Comment by clintandrewhall** [comment]
Same here, 6.5.10.

https://github.com/elastic/kibana/pull/139334

**Comment by IanVS** [comment]
Maybe a solution is to re-export `WebProjectAnnotations` from `@storybook/store` (where it moved to) from `@storybook/preview-web` (where it moved from, and where testing-react is looking for it.

**Comment by sakit0** [comment]
I created a pr.
https://github.com/storybookjs/testing-react/pull/115

**Comment by dakotalightning** [comment]
Fix released in https://github.com/storybookjs/storybook/releases/tag/v6.5.11

**Comment by sakit0** [comment]
It doesn't work until v6.5.10, but specify to use v6.5.11 or later?
