### ISSUE TITLE
Expose types

### ISSUE THREAD

**Issue by pshoniuk** [storybookjs/testing-react#111]
**Is your feature request related to a problem? Please describe.**
I have utils/helpers that work with the results of the composeStory/composeStories functions. Currently, @storybook/testing-react doesn't Expose the types these functions work with. More specifically, I need to use StoryFile and StoriesWithPartialProps.

**Describe the solution you'd like**
It would be great if types were exported and available like this: `import type { StoryFile, StoriesWithPartialProps } from '@storybook/testing-react'`

**Describe alternatives you've considered**
I'm currently importing these types from the dist folder, like this: `import type { StoryFile, StoriesWithPartialProps } from '@storybook/testing-react/dist/types'`. This works, but it's not a good approach.

**Comment by IanVS** [comment]
This is fixed in version [v2.0.0-next.0](https://github.com/storybookjs/testing-react/releases/tag/v2.0.0-next.0).  Please let us know if you still have any problems after updating.
