### ISSUE TITLE
`StoryContext.title` Is Always An Empty String

### ISSUE THREAD

**Issue by DonIsaac** [storybookjs/testing-react#112]
**Describe the bug**
Within a decorator, `StoryContext.title` is always an empty string.

I have a global decorator function that selectively decorates stories based on their top-level group, as specified by the story title. It looks something like this

```tsx
import React from "react";
import { DecoratorFn } from "@storybook/react";
import { Foo, FooContext } from "../src/foo.context";

const defaultFooValue: Foo = {};

const myDecorator: DecoratorFn = (Story, ctx) => {
    const storyGroup = ctx.title.split("/")[0];
    const isFooStory: boolean = storyGroup == "Foo";

    return isFooStory
        ? <FooContext.Provider value={defaultFooValue}><Story /></FooContext.Provider>
        : <Story />
}
```
        
However, even when I test a story whose title is something along the lines of `"Foo/Bar/BazComponent"`, the context is never provided because `isFooStory` is always false. After digging around with a debugger, it appears that `title` (and other properties) are _always_ set to an empty string:

```tsx
// .../node_modules/@storybook/react-testing/dist/testing-react.cjs.development.js, line 181
  var context = {
    componentId: '',
    kind: '',
    title: '',
    id: '',
    name: '',
    story: '',
    argTypes: globalConfig.argTypes || {},
    globals: defaultGlobals,
    parameters: combinedParameters,
    initialArgs: combinedArgs,
    args: combinedArgs,
    viewMode: 'story',
    originalStoryFn: renderFn,
    hooks: new addons.HooksContext()
  };
```

Note that this remains true regardless of whether `composeStory` or `composeStories(stories)` are used. Explicitly providing a story meta object, such as below, additionally has no effect.

```tsx
import { composeStory } from "@storybook/react-testing";
import Meta, { FooStory } from "./Foo.stories";

const FooTestComponent = composeStory(FooStory, Meta);
```

**To Reproduce**
> NOTE: Assumes usage of typescript, jest, and @testing-library/react
1) Create the global decorator above.
2) Export it from `preview.(js|ts)` as normal, use `setGlobalConfig` as normal
3) Create the following component
```tsx
// src/MyComponent.tsx

import React, { FC, useContext } from "react";
import { FooContext } from "foo.context";

export const MyComponent: FC = props => {
    const foo = useContext(FooContext}
    if (!foo) throw new Error("FooContext is missing, no provider found")

    return <div>{String(foo)}</div>
}
```
_(note: I just wrote this inline, it's likely this doesn't work)_

4) Create the FooContext
```tsx
// src/foo.context.ts

import React from "react";

export type Foo = { foo: string }
export const FooContext = React.createContext<Foo | undefined>(undefined); 
```

5) Create a basic Foo Story (similar to the second example on the [What's a Story? Documentation Page](https://storybook.js.org/docs/react/get-started/whats-a-story))
6) Create the following spec file
```tsx
// src/MyComponent.spec.tsx
import React from "react";
import { render } from "@testing-library/react";
import { composeStory } from "@storybook/testing-react";
import Meta, { MyComponentStory } from "./MyComponent.stories";

describe("<MyComponent />", () => {
    it("renders successfully", () => {
        const MyComponent = composeStory(MyComponentStory, Meta);
        const view = render(<MyComponent />);
        expect(view.container.firstElement).toBeInTheDocument();
    })
})
````

When this test file is run, an error is thrown from the assertion within `MyComponent`.

**Expected behavior**
The story's title should be available within the `StoryContext`, allowing the `FooContext` to be provided.

**Screenshots**

**Additional context**

**Comment by yannbf** [comment]
Hey there! I wanted to thank you for using @storybook/testing-react!

`@storybook/testing-react` has been promoted to a first-class Storybook functionality in Storybook 7. This means that you no longer need this package, and this package will not be worked on anymore (especially regarding Storybook 6, unless there are security issues). Instead, you can import the same utilities, but from the `@storybook/react` package. Additionally, the internals of `composeStories` and `composeStory` have been revamped, so the way a story is composed is way more accurate, and it's possible this issue doesn't happen there anymore.

Please do the following:

1. [Upgrade to Storybook 7](https://storybook.js.org/docs/react/migration-guide#page-top) if you haven't already
2. Uninstall `@storybook/testing-react`
3. Update your imports from `@storybook/testing-react` to `@storybook/react`

```diff
// Component.test.jsx
- import { composeStories } from '@storybook/testing-react';
+ import { composeStories } from '@storybook/react';

// setup-files.js
- import { setProjectAnnotations } from '@storybook/testing-react';
+ import { setProjectAnnotations } from '@storybook/react';
```

For now, I'll be closing this issue. Please, if even after migrating, you are still experiencing issues, report them in the [Storybook monorepo](https://github.com/storybookjs/storybook).

Thank you so much for this journey!
