### ISSUE TITLE
Types unknown, not read by Jest

### ISSUE THREAD

**Issue by jayantasamaddar** [storybookjs/testing-react#117]
**Describe the bug**
StoryFn Types are not detected by Jest unless manually forced, making it a verbose process that has to be done for each and every story.

**Framework:** React
**Project:** TypeScript project built with Emotion.js (Using `@emotion/styled`)

### Setup:

In **`Link.story.tsx`**,
```tsx
import React from 'react';
import { ComponentMeta, ComponentStory } from '@storybook/react';

import { Link } from '.';

export default {
  title: 'Components/Link',
  component: Link
} as ComponentMeta<typeof Link>;

const Template: ComponentStory<typeof Link> = (args) => <Link {...args} />;

export const DefaultLink = Template.bind({});
DefaultLink.args = {
  url: 'https://www.github.com/jayantasamaddar/ursa',
  children: 'Visit the Ursa Github page'
};
```

In **`Link.test.tsx`**,
```tsx
import React from 'react';
import { render, screen } from '@testing-library/react';
import { composeStories } from '@storybook/testing-react';
import '@testing-library/jest-dom';
import * as stories from './Link.story'; // import all stories from the stories file
import { lightTheme } from '../../styles';

const { DefaultLink } =  composeStories(stories);

describe('components/Link', () => {
  it('Renders Default Link', () => {
    render(<DefaultLink>Link</DefaultLink>);
    const linkEl = screen.getByTestId('link');
    const linkText = linkEl.querySelector('.Ursa-LinkText');
    expect(linkEl).not.toBeNull();
    expect(linkEl).toHaveAttribute('href', DefaultLink.args.url);
    expect(linkText).toHaveTextContent(linkText.textContent);
    expect(linkEl).toHaveStyle({
      color: lightTheme.color['--ursa-link-primary'],
      'text-decoration': 'underline'
    });
  });
});
```

Getting this error on the `const { DefaultLink } = composeStories(stories);` line above:

Error:
```
const DefaultLink: unknown
JSX element type 'DefaultLink' does not have any construct or call signatures.ts(2604)
```

---

What I did next is, changed the filename `Link.test.tsx` to `Link.test.jsx` to remove the type errors and view the types that show up:
The types showed up as: `const DefaultLink: StoryFn<Partial<LinkProps>>`. Used this as a basis to do a couple of tests for different scenarios.

---

### Scenario 1: Use `StoryFn` and `LinkProps` (my own defined Type interface for the Link component)

So to remove the error, I had to manually do this on the story file, as shown below. 

> **Note:** in the Original file, I was getting away not using the LinkProps and simply using <typeof Link> and letting TypeScript infer the types. Here I had to do a manual import of the LinkProps.

In **`Link.story.tsx`**
```tsx
import React from 'react';
import { ComponentMeta, ComponentStory, StoryFn } from '@storybook/react';

import { Link, LinkProps } from '.';

export default {
  title: 'Components/Link',
  component: Link
} as ComponentMeta<typeof Link>;

const Template: ComponentStory<typeof Link> = (args) => <Link {...args} />;

export const DefaultLink: StoryFn<LinkProps> = Template.bind({});
DefaultLink.args = {
  url: 'https://www.github.com/jayantasamaddar/ursa',
  children: 'Visit the Ursa Github page'
};
```

This has seemed to work as expected as it mimics the behaviour that is expected by default. But the additional hassle of importing this to every story file now remains.

---

### Scenario 2: Use `ComponentStoryFn<typeof Link>`

The idea is to not use LinkProps or a Type specifically but letting TypeScript infer types.

In **`Link.story.tsx`**
```tsx
import React from 'react';
import {
  ComponentMeta,
  ComponentStory,
  ComponentStoryFn
} from '@storybook/react';

import { Link } from '.';

export default {
  title: 'Components/Link',
  component: Link
} as ComponentMeta<typeof Link>;

const Template: ComponentStory<typeof Link> = (args) => <Link {...args} />;

export const DefaultLink: ComponentStoryFn<typeof Link> = Template.bind({});
DefaultLink.args = {
  url: 'https://www.github.com/jayantasamaddar/ursa',
  children: 'Visit the Ursa Github page'
};
```
This too works. However the catch is, this makes the args optional requiring optional chaining to check for validity.

In **`Link.test.tsx`**
```tsx
import React from 'react';
import { render, screen } from '@testing-library/react';
import { composeStories } from '@storybook/testing-react';
import '@testing-library/jest-dom';
import * as stories from './Link.story'; // import all stories from the stories file
import { lightTheme } from '../../styles';

const { DefaultLink } = composeStories(stories);
describe('components/Link', () => {
  it('Renders Default Link', () => {
    render(<DefaultLink>Link</DefaultLink>);
    const linkEl = screen.getByTestId('link');
    const linkText = linkEl.querySelector('.Ursa-LinkText');
    expect(linkEl).not.toBeNull();
    expect(linkEl).toHaveAttribute('href', DefaultLink.args?.url);
    expect(linkText).toHaveTextContent(linkText.textContent);
    expect(linkEl).toHaveStyle({
      color: lightTheme.color['--ursa-link-primary'],
      'text-decoration': 'underline'
    });
  });
});
```

---

**To Reproduce**

Here is a link to a test repo that can be cloned and you can run storybook and jest.
https://github.com/jayantasamaddar/icons-jest-test

- `yarn storybook`
- `yarn test`

---

**Expected behavior**
- Correct type inferring as per **Scenario 1** but working by inferring types like **Scenario 2**.
- Doing so without the usage of any `StoryFn` or `ComponentStoryFn` use.

**Comment by jayantasamaddar** [comment]
Added a link to a repo that can be cloned and immediately checked.

**Comment by jbarreiros** [comment]
Thanks for providing the workarounds @jayantasamaddar.

Ran into the same problem (Storybook 6.5), and option 2 helped. Though, and not sure why, I was able to use `ComponentStory` instead of `ComponentStoryFn`:
```
export const DefaultLink: ComponentStory<typeof Link> = Template.bind({});
```

I tried migrating the stories to CSF3, but that unfortunately didn't help.

**Comment by jayantasamaddar** [comment]
> Thanks for providing the workarounds @jayantasamaddar.
> 
> Ran into the same problem (Storybook 6.5), and option 2 helped. Though, and not sure why, I was able to use `ComponentStory` instead of `ComponentStoryFn`:
> ```
> export const DefaultLink: ComponentStory<typeof Link> = Template.bind({});
> ```
> 
> I tried migrating the stories to CSF3, but that unfortunately didn't help.

Hey, so I ended up creating a VS Code extension that might help you take the guesswork out by using pre-built snippets for the scaffolding - [Storybook Snippets](https://marketplace.visualstudio.com/items?itemName=jayantasamaddar.clk-storybook-snippets&ssr=false#overview)

**Comment by yannbf** [comment]
Hey there! I wanted to thank you for using @storybook/testing-react!

`@storybook/testing-react` has been promoted to a first-class Storybook functionality in Storybook 7. This means that you no longer need this package, and this package will not be worked on anymore (especially regarding Storybook 6, unless there are security issues). Instead, you can import the same utilities, but from the `@storybook/react` package. Additionally, the internals of `composeStories` and `composeStory` have been revamped, so the way a story is composed is way more accurate, and it's possible this issue doesn't happen there anymore.

Please do the following:

1. [Upgrade to Storybook 7](https://storybook.js.org/docs/react/migration-guide#page-top) if you haven't already
2. Uninstall `@storybook/testing-react`
3. Update your imports from `@storybook/testing-react` to `@storybook/react`

```diff
// Component.test.jsx
- import { composeStories } from '@storybook/testing-react';
+ import { composeStories } from '@storybook/react';

// setup-files.js
- import { setProjectAnnotations } from '@storybook/testing-react';
+ import { setProjectAnnotations } from '@storybook/react';
```

For now, I'll be closing this issue. Please, if even after migrating, you are still experiencing issues, report them in the [Storybook monorepo](https://github.com/storybookjs/storybook).

Thank you so much for this journey!
