### ISSUE TITLE
composeStories errors on imports from story files when transpiled with jest

### ISSUE THREAD

**Issue by dptoot** [storybookjs/testing-react#12]
Hey guys!

composeStory works fine but it appears the __esModule key generated by the jest babel transpilation is throwing an error in composeStories when we `export * as stories`.

I receive the error
```
Cannot compose story due to invalid format. @storybook/testing-react expected a function but received boolean instead.
```

I was able to track it down to 

https://github.com/storybookjs/testing-react/blob/main/src/index.ts#L141

```
console.log
    stories {
      __esModule: true,
      Basic: [Function: bound Template],
      PartnerLink: [Function: bound Template] { args: { partner: true } },
      ExternalLink: [Function: bound Template] { args: { external: true } }
    }
```

**Comment by yannbf** [comment]
Hey @dptoot thanks for using this library! And for reporting this issue.

Would it be possible to share a reproduceable repo? Or at least the configuration used in your tests. 
Thanks!

**Comment by jazmon** [comment]
I ran into the same issue.

Here's a patch to fix it with [patch-package](https://github.com/ds300/patch-package) before a real solution is implemented (possibly the same addition in the actual sources?)
```diff
diff --git a/node_modules/@storybook/testing-react/dist/testing-react.cjs.development.js b/node_modules/@storybook/testing-react/dist/testing-react.cjs.development.js
index d0a4f2a..b690926 100644
--- a/node_modules/@storybook/testing-react/dist/testing-react.cjs.development.js
+++ b/node_modules/@storybook/testing-react/dist/testing-react.cjs.development.js
@@ -169,6 +169,8 @@ function composeStories(storiesImport, globalConfig) {
   var composedStories = Object.entries(stories).reduce(function (storiesMap, _ref2) {
     var key = _ref2[0],
         story = _ref2[1];
+    // skip over a transpiler inserted export
+    if (key === '__esModule') return storiesMap
     storiesMap[key] = composeStory(story, meta, globalConfig);
     return storiesMap;
   }, {});
diff --git a/node_modules/@storybook/testing-react/dist/testing-react.esm.js b/node_modules/@storybook/testing-react/dist/testing-react.esm.js
index 0d98a7a..a70651f 100644
--- a/node_modules/@storybook/testing-react/dist/testing-react.esm.js
+++ b/node_modules/@storybook/testing-react/dist/testing-react.esm.js
@@ -158,10 +158,11 @@ function composeStories(storiesImport, globalConfig) {
   var meta = storiesImport["default"],
       stories = _objectWithoutPropertiesLoose(storiesImport, ["default"]); // Compose an object containing all processed stories passed as parameters
 
-
   var composedStories = Object.entries(stories).reduce(function (storiesMap, _ref2) {
     var key = _ref2[0],
         story = _ref2[1];
+    // skip over a transpiler inserted export
+    if (key === '__esModule') return storiesMap
     storiesMap[key] = composeStory(story, meta, globalConfig);
     return storiesMap;
   }, {});

```

**Comment by yannbf** [comment]
Hey @jazmon thanks for the tip! Could you share your setup so I can try to reproduce this issue? thanks!

**Comment by TommyEm** [comment]
Same problem here. I've created a quick stripped-down repo: [https://github.com/TommyEm/testing-react-demo](url)
`yarn test` to repro.

**Comment by dptoot** [comment]
Sorry guys I dropped the ball on that!  😞

**Comment by yannbf** [comment]
No worries at all! Thanks a lot @dptoot for notifying about the issue, thanks @jazmon for the suggestion and thanks @TommyEm for the reproduction repo! All of these were necessary to find a fix. As soon as v0.0.13 is released, I'll let you know and we can all make sure it works for everyone.

**Comment by yannbf** [comment]
There you go, [v0.0.13](https://github.com/storybookjs/testing-react/releases/tag/v0.0.13) has been released and that fixes the problem in your repo @TommyEm! Please let me know if it works well for you @dptoot @jazmon :)

Also, from that repo I saw that in the tests you're using the Args directly. There's no need, as they are processed by testing-react itself!
```diff

 import { composeStories } from '@storybook/testing-react';
 import * as stories from '../Button.stories';

 const { Primary, Secondary } = composeStories(stories);
 test('renders a primary button', () => {
-       render(<Primary {...Primary.args} />);
+       render(<Primary />);
        expect(screen.getByRole('button')).toHaveTextContent('Button');
 });
 test('renders a secondary button', () => {
-       render(<Secondary {...Secondary.args} />);
+       render(<Secondary />);
        expect(screen.getByRole('button')).toHaveTextContent('Button');
 });
 test('matches snapshot', () => {
-       const tree = render(<Primary {...Primary.args} />);
+       const tree = render(<Primary />);
        expect(tree).toMatchSnapshot();
 });
```

**Comment by TommyEm** [comment]
Works fine here.
Good job! Thanks.

**Comment by yannbf** [comment]
I'll be closing this issue, and if someone experiences the bug again let me know and I'll reopen it! Happy testing :)
