### ISSUE TITLE
Run test failed TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by tavria-forever** [storybookjs/testing-react#123]
**Describe the bug**
Get an error when run the jest test.

```
> jest "src/components/MultiChoice/MultiChoice.test.tsx"

 FAIL  src/components/MultiChoice/MultiChoice.test.tsx
  ● Test suite failed to run

    TypeError: Super expression must either be null or a function
```

**To Reproduce**
`jest.config.ts`

```
import type { Config } from '@jest/types';

const config: Config.InitialOptions = {
    moduleNameMapper: {
        '\\.(css|scss)$': '<rootDir>/tests/unit/mocks/styleMock.js',
    },
    moduleDirectories: [
        '.',
        'src',
        'node_modules',
    ],
    preset: 'ts-jest',
    reporters: [
        'default',
        ['jest-html-reporters', {
            publicPath: '__reports/report-unit',
            filename: 'index.html',
        }],
    ],
    testEnvironment: 'jsdom',
    setupFiles: ['<rootDir>/tests/setup.ts'],
};

export default config;
```

`setup.ts`

```
import { setGlobalConfig } from '@storybook/testing-react';

import * as globalStorybookConfig from '../.config/storybook/preview';

setGlobalConfig(globalStorybookConfig);
```

`preview.ts`

```
import { withRouter, withTheme } from '../../lib/storybook';

export const decorators = [
    withRouter,
    withTheme,
];

export const parameters = {
    actions: { argTypesRegex: '^on[A-Z].*' },
    layout: 'fullscreen',
};

export const args = { globalDarkTheme: false };
```

`multiChoice.test.tsx`

```
import React from 'react';

import { composeStories } from '@storybook/testing-react';
import { render } from '@testing-library/react';

import * as stories from './MultiChoice.stories';

const { Full } = composeStories(stories);

describe('MultiChoice', () => {
    test('Render all buttons without cut', () => {
        render(<Full />);
    });
});
```

`Multichoice.stories.tsx`

```
import React from 'react';

import { ComponentMeta, Story } from '@storybook/react';
import { IMultiChoiceCutStyle, IMultiChoiceProps } from 'src/components/MultiChoice/MultiChoice.types';

import { MultiChoice } from '.';

export default {
    title: 'Components/MultiChoice',
    component: MultiChoice,
    argTypes: {
        onSelect: { action: 'select' },
    },
} as ComponentMeta<typeof MultiChoice>;

const Template: Story<IMultiChoiceProps> = args => (
    <div style={{ marginLeft: '16px', marginRight: '16px' }}>
        <MultiChoice {...args} />
    </div>
);

export const Full = Template.bind({});

const items = [
    { id: 2, text: 'Frontend', selected: false },
    { id: 3, text: 'Backend', selected: false },
    { id: 4, text: 'Mobile', selected: false },
];

Full.args = {
    items,
};

```

![2022-11-17_14-53-22](https://user-images.githubusercontent.com/97129287/202439499-cf8377d4-dd6c-47fc-ad26-d0eafa039464.png)

**Additional context**
- jest 22.6.3
- @storybook/react 6.5.9
- @storybook/testing-react 1.3.0
- @testing-library/react 13.4.0

**Comment by tavria-forever** [comment]
I found, that error happens here `node_modules/@storybook/testing-react/dist/testing-react.cjs.development.js:21:29`
```
var React = _interopDefault(require('react'));
```

If I wrap this code into try/catch, the test starts working. 

In package.json I have 
```
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "6.4.2",
    "react-scripts": "5.0.1",
    "ts-node": "10.9.1",
    "ts-openapi": "1.1.4",
    "webpack": "5.74.0"
```

**Comment by Ev-Abbott** [comment]
Did anyone find a solution to this?

**Comment by yannbf** [comment]
Hey there! I wanted to thank you for using @storybook/testing-react!

`@storybook/testing-react` has been promoted to a first-class Storybook functionality in Storybook 7. This means that you no longer need this package, and this package will not be worked on anymore (especially regarding Storybook 6, unless there are security issues). Instead, you can import the same utilities, but from the `@storybook/react` package. Additionally, the internals of `composeStories` and `composeStory` have been revamped, so the way a story is composed is way more accurate, and it's possible this issue doesn't happen there anymore.

Please do the following:

1. [Upgrade to Storybook 7](https://storybook.js.org/docs/react/migration-guide#page-top) if you haven't already
2. Uninstall `@storybook/testing-react`
3. Update your imports from `@storybook/testing-react` to `@storybook/react`

```diff
// Component.test.jsx
- import { composeStories } from '@storybook/testing-react';
+ import { composeStories } from '@storybook/react';

// setup-files.js
- import { setProjectAnnotations } from '@storybook/testing-react';
+ import { setProjectAnnotations } from '@storybook/react';
```

For now, I'll be closing this issue. Please, if even after migrating, you are still experiencing issues, report them in the [Storybook monorepo](https://github.com/storybookjs/storybook).

Thank you so much for this journey!
