### ISSUE TITLE
Nextjs decorators support

### ISSUE THREAD

**Issue by kodai3** [storybookjs/testing-react#133]
**Is your feature request related to a problem? Please describe.**
I know it is known [issue](https://github.com/storybookjs/testing-react/issues/86) and has workaround.

Now with storybook v7, migration commands `npx sb@next upgrade` or `npx storybook@next automigrate` automatically remove `storybook-addon-next` from dependencies, even though I use this on `setupFiles.js`.

```
// setupFiles.js
import { composeConfigs } from '@storybook/testing-react';
import { decorators as nextdecorators } from 'storybook-addon-next/dist/preview';
import * as globalStorybookConfig from './.storybook/preview';

const decorators = [...nextdecorators, ...globalStorybookConfig.decorators];

composeConfigs({
  ...globalStorybookConfig,
  decorators: decorators,
});
```

I think It is more confusing than before.

**Describe the solution you'd like**
I would love to have the official support on this end ideally.

Adding documentation of what part of storybook is "Zero-config" and what is not would be appreciated.

**Comment by kodai3** [comment]
Now the parameter has changed to like this 
```
 parameters: {
    nextjs: {
      router: {
        basePath: '/profile',
      },
    },
  },
```
we  can`t just use `storybook-addon-next` decorators.

Even though I try to access decorators from `@storybook/nextjs`
```
// setupFiles.js
import { decorators as nextjsDecorators } from '@storybook/nextjs';
// throws "_nextjs.decorators is not iterable"
// or like below throws "Cannot find module '@storybook/nextjs/dist/preview' from 'setupFiles.js'"
// import { decorators as nextjsDecorators } from '@storybook/nextjs/dist/preview.mjs';
import { setProjectAnnotations } from '@storybook/react';

const decorators = [...nextjsDecorators];

setProjectAnnotations({
  ...globalStorybookConfig,
  decorators: decorators,
});
```

How can I setup nextjs for testing-react?

**Comment by valentinpalkovic** [comment]
@kodai3 Can you access the necessary decorators via `@storybook/nextjs/preview.js`?

```tsx
import { decorators as nextjsDecorators } from '@storybook/nextjs/preview.js';

```

**Comment by yannbf** [comment]
Hey there! I'm closing this issue, as I believe the suggestion from Valentin will solve it for you.
Feel free to reopen if it doesn't!
