### ISSUE TITLE
Stories that are excluded cause errors

### ISSUE THREAD

**Issue by radfahrer** [storybookjs/testing-react#137]
**Describe the bug**
When a story is excluded from the storybook via `excludeStories` it will throw errors in tests (React Testing Library) that render the story after it has been run through `composeStories`. The error is

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**To Reproduce**
1. Write a story and export it
2. import the story into a test file 
3. use ComposeStories to generate a fixure
4. write a test using React Testing Library to render the fixture
5. run the test and see that it does not throw an error
6. go back to the story file
7. add the story to `excludeStories`
8. rerun the test

**Actual Result**
The error above.

**Expected behavior**

No error.

**Screenshots**
![Screen Shot 2023-02-23 at 11 11 31 AM](https://user-images.githubusercontent.com/418511/221006734-3d1d2ec9-7d92-4f82-a09c-adbd22b55e86.png)

**Additional context**
The reason that this is a problem for us is that we rely heavily on Storys to provide test fixtures for our tests. We also use Apollo's MockedProvider to mock out graph responses. It is common for a Story to be written with specific mocks provided via a custom decorator just for the purposes of running a test with a specific graph response. Since these stories are not visually unique we use `excludeStories` to keep these test fixtures from cluttering up our Storybook. 

Another piece of context is that we have been running `@storybook/testing-react@0.0.21` and are trying to update it to `1.3.0`. `0.0.21` does not throw this error.

**Comment by radfahrer** [comment]
I just found a workaround. It seems that this error only happens with `composeStories` if I use `composeStory` the error does not occur.

**Comment by yannbf** [comment]
Hey there! I wanted to thank you for using @storybook/testing-react!

`@storybook/testing-react` has been promoted to a first-class Storybook functionality in Storybook 7. This means that you no longer need this package, and this package will not be worked on anymore (especially regarding Storybook 6, unless there are security issues). Instead, you can import the same utilities, but from the `@storybook/react` package. Additionally, the internals of `composeStories` and `composeStory` have been revamped, so the way a story is composed is way more accurate, and it's possible this issue doesn't happen there anymore.

Please do the following:

1. [Upgrade to Storybook 7](https://storybook.js.org/docs/react/migration-guide#page-top) if you haven't already
2. Uninstall `@storybook/testing-react`
3. Update your imports from `@storybook/testing-react` to `@storybook/react`

```diff
// Component.test.jsx
- import { composeStories } from '@storybook/testing-react';
+ import { composeStories } from '@storybook/react';

// setup-files.js
- import { setProjectAnnotations } from '@storybook/testing-react';
+ import { setProjectAnnotations } from '@storybook/react';
```

For now, I'll be closing this issue. Please, if even after migrating, you are still experiencing issues, report them in the [Storybook monorepo](https://github.com/storybookjs/storybook).

Thank you so much for this journey!
