### ISSUE TITLE
Support CSF 3.0

### ISSUE THREAD

**Issue by kluplau** [storybookjs/testing-react#31]
I'm checking out CSF 3.0 (hidden behind a feature flag).

The stories can now be an object

```typescript
export default {
  title: "Components/Button",
  component: Button
} as Meta;

export const Default = {
  args: {
    loading: false,
    block: false,
    disabled: false,
    children: "Default button",
  },
};
```

I get this error, when trying to use CSF 3.0 stories with composeStories. 

```text
Cannot compose story due to invalid format. @storybook/testing-react expected a function but received object instead.
    >  8 | const { Default } = composeStories(stories);
```

I tried browsing Storybooks code-base to find a utility function that converts CSF 3.0 objects to functions, but wasn't able to find it.

**Comment by yannbf** [comment]
Hey @kluplau thanks a lot for using this library! CSF 3.0 is still under experimental phase and can likely change soon, but I will try my best to add experimental support for it as well!

**Comment by yannbf** [comment]
[0.0.21 has been released](https://github.com/storybookjs/testing-react/releases/tag/v0.0.21) to support CSF3! I'll be closing the issue, please update the lib and let me know how it goes for you!

**Comment by yannbf** [comment]
Hey everyone! Given that there was a breaking change in `v0.0.21`, I had to revert it and make a prerelease with a breaking change that supports CSF3.

To try it out, please install `v1.0.0-next.0` and try it out, but keep in mind you need Storybook 6.4 if you're using typescript.
