### ISSUE TITLE
Support for Story.storyName

### ISSUE THREAD

**Issue by synaptiko** [storybookjs/testing-react#49]
Storybook allows to specify `storyName` but when using `composeStories` this information is not available anymore. I can access it if I import the story directly though.

Example:
```
// In stories file:
CurrentPlan.storyName = 'Current plan';
...
// In Jest test:
import * as stories from 'components/Header.stories';
import { render } from '@testing-library/react';
import { composeStories } from '@storybook/testing-react';

test.each(Object.values(composeStories(stories)).map((Story) => [Story.storyName!, Story]))(
  'renders Header for %s story',
  (_storyName, Story) => {
    const tree = render(<Story />);
    expect(tree.baseElement).toMatchSnapshot();
  }
);
```

**Comment by yannbf** [comment]
Hey @synaptiko thanks a lot for opening this issue! Incredible idea you have over there, which can be used for snapshot testing, SSR, a11y and many more examples. I just released version `1.2.0` which should support that, and I took the liberty to use your example in the [README](https://github.com/storybookjs/testing-react#batch-testing-all-stories-from-a-file).

Thanks!
