### ISSUE TITLE
Fails to recognize non-story exports and exclude them from composeStories.

### ISSUE THREAD

**Issue by luciddr34m3r** [storybookjs/testing-react#50]
**Describe the bug**
I receive the following error when exporting non-story constants from my stories via the `includeStories` syntax.

`Cannot compose story due to invalid format. @storybook/testing-react expected a function but received object instead.`

The offending line:

`const { Default, WithHeading, } = composeStories(stories);`

The relevant story snippet:

```
export default {
  title: 'Components/CashDisplay',
  component: CashDisplay,
  includeStories: /^[A-Z]/,
};

export const data = {
  default: {
    amount: 5.25,
  }
}
```

**To Reproduce**
1. Create a story
2. Add a parameter that allows you to export a non-story object
3. Use composeStory on that story.

**Expected behavior**
The testing framework should respect storybook's methods for turning some exports into stories and not others, and composeStories should properly recognize which exports are and aren't stories.

**Additional context**
Stack trace:

```
      at composeStory (node_modules/@storybook/testing-react/src/index.ts:63:11)
      at reduce (node_modules/@storybook/testing-react/src/index.ts:173:25)
          at Array.reduce (<anonymous>)
      at composeStories (node_modules/@storybook/testing-react/src/index.ts:171:51)
      at Object.<anonymous> (src/test/components/REDACTED.test.js:6:35)
```

**Comment by yannbf** [comment]
Hey @luciddr34m3r thanks a lot for opening this issue! The feature is now supported in v1.1.0!
Thanks for you patience and for using this library <3
