### ISSUE TITLE
Adding notes to a story breaks composeStories

### ISSUE THREAD

**Issue by sdaconceicao** [storybookjs/testing-react#51]
**Describe the bug**
If you have a story file which contains notes added directly onto any stories within in, even if you use a story without those notes, composeStories fails.

**To Reproduce**
1. Create a story with notes added to that individual story
export default {
  title: 'Test',
  component: Test,
  parameters: {
    notes: 'Lorem Ipsum'
  }
};
export const Example = () => (
  <ProgressBar message="I am a stalled progress bar" progress={25} dataQa="progress-stalled" />
);
export const Example2 = () => (
  <ProgressBar message="I am a stalled progress bar" progress={25} dataQa="progress-stalled" />
);
Example2.story = {
  parameters: {
    notes: 'Notes for example 2'
  }
}

2. Create a cypress spec that imports a story from that file
import * as stories from '../../stories/Test.stories';

const { Example } = composeStories(stories);

describe('Test', () => {
  describe('Usage', () => {
    beforeEach(() => {
      mount(<Example />);
    });
    it('renders', () => {
      expect();
    });
  });
});

**Expected behavior**
Tests should work

**Current Behavior**
The following error originated from your test code, not from Cypress.

  > StoryFn.story object-style annotation is not supported. @storybook/testing-react expects hoisted CSF stories.

**Comment by yannbf** [comment]
Hey @sdaconceicao, thanks for using testing-library!
The error is not related to addon-notes. It's that your stories are not hoisted, which is something that was deprecated in Storybook 6.0.

You can quickly fix that by using the codemod in the [instructions here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#hoisted-csf-annotations). Let me know if it works out for you!

**Comment by sdaconceicao** [comment]
Hey @yannbf,
That seems to have done the trick. The docs on the notes addon were what I following and should probably be updated.
https://www.npmjs.com/package/@storybook/addon-notes#using-markdown

**Comment by yannbf** [comment]
> Hey @yannbf,
> That seems to have done the trick. The docs on the notes addon were what I following and should probably be updated.
> https://www.npmjs.com/package/@storybook/addon-notes#using-markdown

Great to hear! I'm not sure which version of storybook you're using, but notes has been deprecated about two years ago and I believe you should use addon-docs instead. There are migration instructions in the addon repository!
