### ISSUE TITLE
Module not found: Can't resolve '@storybook/react/types-6-0'

### ISSUE THREAD

**Issue by gvocale** [storybookjs/testing-react#55]
**Describe the bug**
After upgrading to Next 12, when running Cypress component tests I get the following error. This only happens during Cypress component test. Cypress component test is using `import { composeStories } from "@storybook/testing-react";` to import and test the story. Has anyone run into this issue before?

Downgrading to Next 11 solves the issue.

```tsx
Module not found: Can't resolve '@storybook/react/types-6-0'
```

Cross post from here https://github.com/storybookjs/storybook/issues/16672, sorry just realized after this could be a better place to ask for help.

**Comment by yannbf** [comment]
Hey @gvocale that's an odd error. What versions are you using, both for @storybook/react and @storybook/testing-react?

Could you try upgrading and see if the error is still there?

**Comment by gvocale** [comment]
I figure out I needed to update the import to:
```
import { Meta, Story } from "@storybook/react";
```

**Comment by yannbf** [comment]
> I figure out I needed to update the import to:
> 
> ```
> import { Meta, Story } from "@storybook/react";
> ```

Great you found that out!
