### ISSUE TITLE
Story's argTypes defaultValue is not used

### ISSUE THREAD

**Issue by sawyerh** [storybookjs/testing-react#56]
**Describe the bug**

A Story's `argTypes` entries can have a `defaultValue`, which can be used if a value isn't defined in `args`. 

**To Reproduce**

Given a Story meta of:

```tsx
export default {
  title: 'Example/Button',
  component: Button,
  argTypes: {
    children: { control: 'text', defaultValue: 'Default button text' },
  },
} as Meta;

const Template: Story<ButtonProps> = (args) => <Button {...args} />;

export const Primary = Template.bind({});
Primary.args = {
  size: 'large',
  primary: true,
};
```

**Expected behavior**

The button when rendered in tests should result in a button with text of "Default button text", as it does in Storybook:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/371943/141598280-61f06ecf-dbd0-47e2-af94-da0610b9c8cc.png">

**Comment by jmorrice** [comment]
+1 :)

**Comment by yannbf** [comment]
Hey there! I wanted to thank you for using @storybook/testing-react!

`@storybook/testing-react` has been promoted to a first-class Storybook functionality in Storybook 7. This means that you no longer need this package, and this package will not be worked on anymore (especially regarding Storybook 6, unless there are security issues). Instead, you can import the same utilities, but from the `@storybook/react` package. Additionally, the internals of `composeStories` and `composeStory` have been revamped, so the way a story is composed is way more accurate, and it's possible this issue doesn't happen there anymore.

Please do the following:

1. [Upgrade to Storybook 7](https://storybook.js.org/docs/react/migration-guide#page-top) if you haven't already
2. Uninstall `@storybook/testing-react`
3. Update your imports from `@storybook/testing-react` to `@storybook/react`

```diff
// Component.test.jsx
- import { composeStories } from '@storybook/testing-react';
+ import { composeStories } from '@storybook/react';

// setup-files.js
- import { setProjectAnnotations } from '@storybook/testing-react';
+ import { setProjectAnnotations } from '@storybook/react';
```

For now, I'll be closing this issue. Please, if even after migrating, you are still experiencing issues, report them in the [Storybook monorepo](https://github.com/storybookjs/storybook).

Thank you so much for this journey!
