### ISSUE TITLE
@storybook/testing-react type errors

### ISSUE THREAD

**Issue by rexkenley** [storybookjs/testing-react#62]
**Describe the bug**
I am getting the following ts errors with my code while trying to use the new composeStories.

![image](https://user-images.githubusercontent.com/10548251/144448796-66f4a787-e2b8-45e9-998c-58e36a621347.png)
![image](https://user-images.githubusercontent.com/10548251/144448853-1c58379d-652d-48bf-b202-24514cfd1fd0.png)

I was able to "fix" it by using casting, but I don't think this is right.

![image](https://user-images.githubusercontent.com/10548251/144449232-26b68937-2241-44e6-abd2-924c62cc9cfe.png)

What should I do?

Storybook version: 6.4.4

**Comment by yannbf** [comment]
Hey @rexkenley thanks for opening this issue! Could you provide an example of how your stories look like? Thanks!

**Comment by robcaldecott** [comment]
I am seeing the same with 6.4.

This story works (if I use `Meta`):

```tsx
import { Meta, ComponentStory } from "@storybook/react";
import { Logo } from ".";

export default {
  component: Logo,
} as Meta;

const Template: ComponentStory<typeof Logo> = (args) => <Logo {...args} />;

export const Default = Template.bind({});
Default.args = {
  width: 200,
  fill: "#3C576B",
};
```

This story does not work (using `ComponentMeta`):

```tsx
import { ComponentStory, ComponentMeta } from "@storybook/react";
import { Logo } from ".";

export default {
  component: Logo,
} as ComponentMeta<typeof Logo>;

const Template: ComponentStory<typeof Logo> = (args) => <Logo {...args} />;

export const Default = Template.bind({});
Default.args = {
  width: 200,
  fill: "#3C576B",
};
```

The test import looks like this:

```js
import { render, screen } from "@testing-library/react";
import { composeStories } from "@storybook/testing-react";
import * as stories from "./Logo.stories";

// TS2345
const { Default } = composeStories(stories);
```

Full error when using `ComponentMeta`:

```
Argument of type 'typeof import("/Users/caldecor/Projects/storybook-64/src/Logo/Logo.stories")' is not assignable to parameter of type 'StoryFile'.
  Types of property 'default' are incompatible.
    Type 'ComponentMeta<({ height, width, fill }: LogoProps) => Element>' is not assignable to type 'Meta<Args>'.
      Type 'ComponentMeta<({ height, width, fill }: LogoProps) => Element>' is not assignable to type 'BaseAnnotations<ReactFramework, Args>'.
        Types of property 'decorators' are incompatible.
          Type 'DecoratorFunction<ReactFramework, LogoProps>[] | undefined' is not assignable to type 'DecoratorFunction<ReactFramework, Args>[] | undefined'.
            Type 'DecoratorFunction<ReactFramework, LogoProps>[]' is not assignable to type 'DecoratorFunction<ReactFramework, Args>[]'.
              Type 'DecoratorFunction<ReactFramework, LogoProps>' is not assignable to type 'DecoratorFunction<ReactFramework, Args>'.
                Types of parameters 'c' and 'c' are incompatible.
                  Type 'StoryContext<ReactFramework, Args>' is not assignable to type 'StoryContext<ReactFramework, LogoProps>'.
                    Type 'StoryContext<ReactFramework, Args>' is not assignable to type '{ component?: ComponentType<any> | undefined; subcomponents?: Record<string, ComponentType<any>> | undefined; parameters: Parameters; initialArgs: LogoProps; argTypes: StrictArgTypes<...>; }'.
                      Types of property 'initialArgs' are incompatible.
                        Type 'Args' is not assignable to type 'LogoProps'.ts(2345)
```

**Comment by rexkenley** [comment]
robcaldecott pretty much nailed it. After I implemented what he did, I got new ts errors.
![image](https://user-images.githubusercontent.com/10548251/144679152-89d9bcfb-24c0-4a49-ba0e-70a53eb34d78.png)
![image](https://user-images.githubusercontent.com/10548251/144679184-774cbfeb-e5bd-4f58-bd95-9fb4d36f4cd5.png)

**Comment by phenrique7** [comment]
I'm experienced the same type errors when I upgraded sb to 6.4. My workaround was to use `Meta` instead of `ComponentMeta`, as [@robcaldecott reported](https://github.com/storybookjs/testing-react/issues/62#issuecomment-985635505).

**Comment by yannbf** [comment]
Hey @phenrique7 could you show the example of the component that fails? Is that component typed in any way or does it look like this?
```js
// no types at all, just auto-inferred JSX.Element
const MyComponent = () => <div>HelloWorld</div>
```

**Comment by phenrique7** [comment]
@yannbf, I created a reproducible repo: https://github.com/phenrique7/storybook-testing-react-type-errors. Hope this can help.

**Comment by rexkenley** [comment]
@yannbf 
Here is the repo: https://github.com/rexkenley/rollupError
The story is here https://github.com/rexkenley/rollupError/tree/main/stories/components/Timesheet

**Comment by yannbf** [comment]
Thanks @phenrique7 and @rexkenley for the repros, that helps me a ton!! 
I'll work on it likely tomorrow and release a fix as soon as possible, and make sure to test the fix on both your repos.

have a great weekend!

**Comment by yannbf** [comment]
Hey everyone, I released a fix in [v1.2.1](https://github.com/storybookjs/testing-react/releases/tag/v1.2.1) that should address this issue.

The repros you provided were super helpful and I made sure to test in each one of them.

@rexkenley I noticed a few things in your repo and I'll make a PR explaining the correct usage of this library!

@phenrique7 I saw the easter egg there 😂  Muito obrigado!

**Comment by rexkenley** [comment]
@yannbf Thank you so much to fixing this so quickly. I am looking forward to the correct usage link.

**Comment by yannbf** [comment]
> @yannbf Thank you so much to fixing this so quickly. I am looking forward to the correct usage link.

No worries, thanks for using the library!

I opened the PR at https://github.com/rexkenley/rollupError/pull/1
