### ISSUE TITLE
Tests that use "play" pass even if interactions fail

### ISSUE THREAD

**Issue by robcaldecott** [storybookjs/testing-react#69]
I am using `@storybook/testing-react@1.2.0` and if I execute the `play` function from a test it will always pass, even if the interactions do not actually work in Storybook.

For example, take the following story that clicks on a "Home" button which I have deliberately broken:

```tsx
HomeBreadcrumb.play = async ({ canvasElement }) => {
  const canvas = within(canvasElement);
  // Wait for the card to load
  await canvas.findByLabelText(/vehicle details/i);
  // Click the Home button THIS WILL FAIL
  userEvent.click(canvas.getByRole("link", { name: /home2/i }));
  // Wait for the home page
  await canvas.findByRole("heading", { name: /home/i, level: 1 });
};
```

In Storybook the debug interaction console shows an error:

![image](https://user-images.githubusercontent.com/796702/144816771-682624cf-b21a-4272-8c48-8c96d5b3132e.png)

I then have a test like this:

```tsx
import { composeStories } from "@storybook/testing-react";
import * as stories from "./Details.stories";

const { HomeBreadcrumb } = composeStories(stories);

test("home breadcrumb", async () => {
  const { container } = render(<HomeBreadcrumb />);
  // @ts-ignore
  await HomeBreadcrumb.play({ canvasElement: container });
});
```

But the test passes. Am I missing something here?

**Comment by robcaldecott** [comment]
I created a sample repo that shows this issue:

https://github.com/robcaldecott/storybook-testing-play-issue

`npm test` and both tests pass even though one of the stories play functions fails to interact.

**Comment by robcaldecott** [comment]
@yannbf sorry to tag you directly! but is there any way to assert if `play` fails? Or is this not supported?

**Comment by robcaldecott** [comment]
Just updated to `@storybook/testing-react` `1.2.2` and the issue is resolved! 🥳

**Comment by yannbf** [comment]
Hey @robcaldecott sorry for not jumping in this issue until now. It was definitely a bug!
I was fixing other stuff in the library and it so happened to have fixed this issue as well! I _really_ appreciate that you opened this issue as well as made a reproduction repo. Thank you so much for using this library!
