### ISSUE TITLE
Support for includeStories/excludeStories parameter

### ISSUE THREAD

**Issue by yannbf** [storybookjs/testing-react#7]
Storybook has support for [non-story exports](https://github.com/storybookjs/storybook/pull/9100). There are developers using this in their projects, and this lib should respect that configuration.

**Comment by evasconcelos** [comment]
Just got the following error and end up here 
`Cannot compose story due to invalid format. @storybook/testing-react expected a function but received string instead.`

i guess i wont export anything else then stories for now 😢

**Comment by yannbf** [comment]
Hey @evasconcelos the feature is now supported in v1.1.0!
Thanks for you patience and for using this library <3
