### ISSUE TITLE
argsEnhancers are not applied

### ISSUE THREAD

**Issue by pmelab** [storybookjs/testing-react#78]
**Is your feature request related to a problem? Please describe.**

The interactions addon replaces action arguments with jest mocks that can be inspected in play functions. It would be great to be able to run play functions in jest to test them during CI. This currently does not work because the arguments don't get enhanced.

**Describe the solution you'd like**
`argsEnhancers` from global config or other presets should be applied. Then it would be possible to use ...

https://github.com/storybookjs/testing-react#interactions-with-play-function

... in combination with ...

https://storybook.js.org/docs/react/essentials/interactions#writing-interactions

Or specifically the `await waitFor(() => expect(args.onSubmit).toHaveBeenCalled());` part.

I think this would have to happen during argument combination:
https://github.com/storybookjs/testing-react/blob/main/src/index.ts#L121-L124

**Comment by yannbf** [comment]
Hey there! I wanted to thank you for using @storybook/testing-react!

`@storybook/testing-react` has been promoted to a first-class Storybook functionality in Storybook 7. This means that you no longer need this package, and this package will not be worked on anymore (especially regarding Storybook 6, unless there are security issues). Instead, you can import the same utilities, but from the `@storybook/react` package. Additionally, the internals of `composeStories` and `composeStory` have been revamped, so the way a story is composed is way more accurate, and it's possible this issue doesn't happen there anymore.

Please do the following:

1. [Upgrade to Storybook 7](https://storybook.js.org/docs/react/migration-guide#page-top) if you haven't already
2. Uninstall `@storybook/testing-react`
3. Update your imports from `@storybook/testing-react` to `@storybook/react`

```diff
// Component.test.jsx
- import { composeStories } from '@storybook/testing-react';
+ import { composeStories } from '@storybook/react';

// setup-files.js
- import { setProjectAnnotations } from '@storybook/testing-react';
+ import { setProjectAnnotations } from '@storybook/react';
```

For now, I'll be closing this issue. Please, if even after migrating, you are still experiencing issues, report them in the [Storybook monorepo](https://github.com/storybookjs/storybook).

Thank you so much for this journey!
