### ISSUE TITLE
Path to support Mocha (for Meteor)?

### ISSUE THREAD

**Issue by eric-burel** [storybookjs/testing-react#87]
**Is your feature request related to a problem? Please describe.**
I am stuck with Meteor.js, where Jest is currently a no go because it would require a too complicated setup, with a lot of mocks.
It is slightly easier to use Storybook though, since it concerns only the frontend part, so I am investigating if supporting it is worth it or not.

Do you thing it would doable to use this plugin in a Mocha testing environment? What could be the main blocker?

**Comment by yannbf** [comment]
Hey @eric-burel that's a very interesting question. @storybook/testing-react does not have anything to do with test runners, even though the name might be a bit misleading. This library really just composes stories so you can have a single component that contains all the configuration. 

Having said that, as long as you have Mocha setup in your project to render components using something like enzyme or testing-library, using @storybook/testing-react should be possible! If you're using `setupGlobalConfig`, you might need to use a similar mechanism in Mocha than the setup files in Jest.

**Comment by eric-burel** [comment]
Ok perfect, indeed I see no real dependency from the code, thank you! I'll try to reexplore Meteor+Storybook a bit, we had a working loader in the past for loading packages and mocks for core Meteor code but it broke with TypeScript, I'd like to test another approach with Babel to replace the imports. Testing Library is supposed to work ok with Mocha as well so it may work.
