### ISSUE TITLE
composeStories should support Meta typed with generic

### ISSUE THREAD

**Issue by sowes** [storybookjs/testing-react#91]
## The problem

I would like to apply a generic type to the Meta type for my default story exports. Doing so enables type-checking on the values defined on the args attribute in the default export. However, by applying this type, the composeStories function I am using for my tests fails. It appears as though, after digging through some type files, that composeStories does not take into account generics for Meta.

_demo.stories.tsx_
```typescript
import { Meta, Story } from '@storybook/react';

interface DemoProps {
  foo: string;
  baz: boolean;
}

export default {
  title: 'MyComponent',
  component: MyComponent,
  args: {
    foo: 'baa',
    baz: false
  },
  argTypes: {
    foo: { control: { type: 'text' } },
    baz: { control: { type: 'boolean' } }
  }
} as Meta<DemoProps>;

export const StoryDemo: Story<DemoProps> = (args: DemoProps) => {
  return <MyComponent foo={args.foo} baz={args.baz} />;
};
```

_demo.test.ts_
```typescript
import { composeStories } from '@storybook/testing-react';

import * as stories from './demo.stories';

const { StoryDemo } = composeStories(stories);
```

The errors I receive in my test file:

`Property 'StoryDemo' does not exist on type 'StoriesWithPartialProps<{ default: Meta<Args>; __esModule?: boolean | undefined; }>'.`

`Type 'StoryContext<ReactFramework, Args>' is not assignable to type 'StoryContext<ReactFramework, DemoProps>'.
                    Type 'StoryContext<ReactFramework, Args>' is not assignable to type '{ component?: ComponentType<any> | undefined; subcomponents?: Record<string, ComponentType<any>> | undefined; parameters: Parameters; initialArgs: DemoProps; argTypes: StrictArgTypes<...>; }'.
                      Types of property 'initialArgs' are incompatible.
                        Type 'Args' is not assignable to type 'DemoProps'.`

## Potential solution

I noticed that the composeStory function accepts a generic that is applied to the story itself, but not on the meta parameter. When I modified the @storybook/texting-react type declaration from node_modules for this function to the following, I was able to get it to work in my test.

_index.d.ts_
```typescript
function composeStory<GenericArgs>(story: Story<GenericArgs>, meta: Meta<GenericArgs>, globalConfig?: GlobalConfig): Story<Partial<GenericArgs>>;
```

_demo.test.ts_
```typescript
import { composeStory } from '@storybook/testing-react';

import meta, { DemoProps, StoryDemo } from './demo.stories';

const { StoryDemoTest } = composeStory<DemoProps>(StoryDemo, meta);
```

I would prefer if a similar solution could be applied to the composeStories function. Ideally, these compose functions could just accept any type set on Meta and apply it within its own implementation.

**Comment by yannbf** [comment]
Hey there! I wanted to thank you for using @storybook/testing-react!

`@storybook/testing-react` has been promoted to a first-class Storybook functionality in Storybook 7. This means that you no longer need this package, and this package will not be worked on anymore (especially regarding Storybook 6, unless there are security issues). Instead, you can import the same utilities, but from the `@storybook/react` package. Additionally, the internals of `composeStories` and `composeStory` have been revamped, so the way a story is composed is way more accurate, and it's possible this issue doesn't happen there anymore.

Please do the following:

1. [Upgrade to Storybook 7](https://storybook.js.org/docs/react/migration-guide#page-top) if you haven't already
2. Uninstall `@storybook/testing-react`
3. Update your imports from `@storybook/testing-react` to `@storybook/react`

```diff
// Component.test.jsx
- import { composeStories } from '@storybook/testing-react';
+ import { composeStories } from '@storybook/react';

// setup-files.js
- import { setProjectAnnotations } from '@storybook/testing-react';
+ import { setProjectAnnotations } from '@storybook/react';
```

For now, I'll be closing this issue. Please, if even after migrating, you are still experiencing issues, report them in the [Storybook monorepo](https://github.com/storybookjs/storybook).

Thank you so much for this journey!
