### ISSUE TITLE
Support React@18

### ISSUE THREAD

**Issue by alejandronanez** [storybookjs/testing-react#99]
**Describe the bug**
I'm currently using React 18 in my project and I'm having issues when I try to install this package because of the react version specified in https://github.com/storybookjs/testing-react/blob/d22cb1c397f273c382aff7920d7d97147d415f83/package.json#L81

Is there anything I can do to help? I suppose I can open a PR to update the peerDeps, but I'm not familiar with the project so I don't know if that fix is going to be "that simple"

**To Reproduce**

I can create a repo to reproduce this later today if that's helpful.

**Expected behavior**
I can install the library

**Screenshots**
![](https://cdn.zappy.app/9641cd2b42a2094e0fe9e24fd8986439.png)
**Additional context**

**Comment by alejandronanez** [comment]
Just opened this, https://github.com/storybookjs/testing-react/pull/100 I'm not sure if that's enough!

**Comment by PeterSHL** [comment]
Any idea when this change will be released?

**Comment by hkai-jackylo** [comment]
> Any idea when this change will be released?

Would like to know too!

**Comment by yannbf** [comment]
Hey everyone! Sorry about this, the PR was not labeled correctly before getting merged. This should be out now in 1.3.0!
